---

- name: Update package cache
  ansible.builtin.package:
    update_cache: yes

- name: Allow incoming SSH traffic from source port 22
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 22
    state: present
    ctstate: NEW,ESTABLISHED
    jump: ACCEPT

- name: Allow outgoing SSH connections (ESTABLISHED)
  ansible.builtin.iptables:
    chain: OUTPUT
    protocol: tcp
    source_port: 22
    state: present
    ctstate: ESTABLISHED
    jump: ACCEPT

- name: Install netfilter-persistent
  package:
    name: '{{ netfilter_persistent_service }}'
    state: present

- name: Save iptables rules in Debian/Ubuntu
  ansible.builtin.command: iptables-save > /etc/iptables/rules.v4
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: Save iptables rules in CentOS/RHEL
  ansible.builtin.command: service iptables-save
  when: ansible_distribution in ['CentOS', 'RHEL']

- name: Save iptables rules
  ansible.builtin.service:
    name: '{{ netfilter_persistent_service }}'
    state: restarted
    enabled: true
